version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - geraete_mysql_data:/var/lib/mysql

volumes:
  geraete_mysql_data:
    name: geraeteverwaltung_mysql_data
    driver: local
